//! The window's stylesheet, inline.
//!
//! One string in the binary rather than an asset: the shell is one screen and
//! nothing it needs is resolved at run time (§15 q1 — packaging is not this
//! ticket's ground), so a stylesheet the app cannot start without has no
//! business arriving over a resolver. It is Tailwind and daisyUI's output —
//! generated by Node from [`style/input.css`](../style/input.css), committed to
//! the tree, and compiled in here by `include_str!`
//! (`docs/adr/0003-the-stylesheet-is-generated-and-committed.md`). `npm run css`
//! regenerates it and `npm run css:check` fails when the committed file is not
//! what the source produces; `cargo run` needs neither.
//!
//! **The rules are in the source stylesheet and so are the tests below.** A
//! generated file is nothing but declarations — its comments are stripped and
//! its formatting is the formatter's — so what these tests read is the file a
//! person edits, which is also the only file where failing one of them is
//! something to fix.
//!
//! **The window is the drawing** (`docs/adr/0009-the-window-is-the-drawing.md`).
//! The palette, the type scale, the control heights and the two animations are
//! the design's own, and the names below are the design's names: `bg`, `panel`,
//! `panel2`, `sunk`, `line`, `line2`, `txt`, `dim`, `dim2`, `acc`, and the five
//! hues that mean something — `out` for a frame this client sent, `in` for one
//! the agent sent and for a turn waiting on the reader, `ok`, `err`, and `vio`
//! for traffic nobody has a name for. Those five mean the same thing in both
//! schemes, or a screenshot stops being readable evidence.
//!
//! **Every colour in the source is a token, and no rule outside the blocks near
//! the top carries a literal.** A literal anywhere else is a rule that only
//! works in one scheme, which is the whole failure mode this arrangement exists
//! to make impossible. The dark values are written out twice — once in the media
//! query, once in the `data-theme` block — because CSS has no way to say "these
//! declarations, under either of two conditions", and a change to one is a
//! change owed to the other. That used to be review's to catch and is a test's
//! now: review missed it the first time it mattered, and the half it missed was
//! the half `Appearance → Dark` shows.
//!
//! **And no class can carry one either.** That rule is asserted over the rules a
//! person writes here, and a class name lives in a Rust file where no test in
//! this module can see it — so the vocabulary (`theme.css`) clears Tailwind's
//! colour namespace before declaring this window's, which is what makes
//! `bg-red-500` not exist rather than merely discouraged. daisyUI owns the
//! components and both themes; these rules say what the drawing paints them in.
//!
//! ## What the palette clears, and what it does not
//!
//! The floor is WCAG AA: 4.5:1 for text against every ground it rests on, 3:1
//! for a boundary or a signal. **The palette is the drawing's, and three of its
//! values are below the text floor** — `--dim2` in both schemes, and `--out` and
//! `--ok` in light. That is a reversal, taken deliberately (ADR 0009): an earlier
//! ring raised them and the design is what this window is now, so the values are
//! the drawing's and the exceptions are *named, measured and held* by
//! `the_palette_is_the_drawings_and_every_value_below_the_text_floor_is_named`
//! below — which fails if any of the three drifts lower, and fails if a fourth
//! joins them.
//!
//! Everything in that set clears 3:1, which is the floor for a signal, and
//! nothing in this window is known by colour alone: an unadvertised capability
//! row states its answer in words, a frame's direction is an arrow and a word,
//! and every dot repeats what its row says. `--line` and `--line2` are the two
//! hairlines and are decoration in both schemes for the reason they always were:
//! at 3:1 a line drawn on every row and every panel is a grid over a dense tool.

/// The generated stylesheet, as the root component inlines it into `<style>`.
///
/// `include_str!` of a committed build artifact: nothing resolves it and
/// nothing generates it at build time, so a checkout with a Rust toolchain
/// builds a window that is painted (ADR 0003).
pub const SHEET: &str = include_str!("../style/sheet.css");

/// The stylesheet as it is written, which is what the tests below read.
///
/// Two files rather than one, in the order the build reads them: `theme.css`
/// declares retained inspector names and semantic aliases, while `input.css`,
/// which imports it, declares layout and behaviour.
///
/// Concatenated here because every test below asks a question about the source
/// as a whole — where a colour literal may appear, what a rule names — and that
/// question does not change because the text arrives in two pieces.
#[cfg(test)]
const SOURCE: &str = concat!(
    include_str!("../style/theme.css"),
    include_str!("../style/input.css"),
);

#[cfg(test)]
mod tests {
    use super::{SHEET, SOURCE};

    /// The declarations of the one rule with this exact selector.
    fn rule(selector: &str) -> &'static str {
        let opens = format!("\n{selector} {{");
        SOURCE
            .split_once(opens.as_str())
            .unwrap_or_else(|| panic!("`{selector}` is a rule in the sheet"))
            .1
            .split_once('}')
            .expect("the rule is closed")
            .0
    }

    /// The source with its prose taken out, for the tests that read the whole
    /// file rather than one rule.
    ///
    /// Every one of them asks what the *declarations* say, and a comment is
    /// where this sheet explains itself — routinely by naming the very thing
    /// the test forbids a rule to name. A scan that could not tell the two
    /// apart would make the explanation the violation.
    fn declarations() -> String {
        let mut left = SOURCE;
        let mut kept = String::with_capacity(SOURCE.len());
        while let Some((before, rest)) = left.split_once("/*") {
            kept.push_str(before);
            left = rest.split_once("*/").expect("a comment is closed").1;
        }
        kept.push_str(left);
        kept
    }

    /// Every rule that declares something, as `(nesting, declarations)`.
    ///
    /// The nesting is what the rule is inside, outermost first, ending in its
    /// own selector: `["@media (prefers-color-scheme: dark)", ":root:not(…)"]`.
    /// Three at-rules in this sheet wrap other rules — the two media queries and
    /// the keyframes — and a caller that could not see *which* would either hold
    /// a keyframe's stops to the rules a selector obeys or miss half the palette.
    ///
    /// A block that holds only other blocks declares nothing and is not
    /// returned; it is only ever the head of somebody else's nesting.
    fn rules() -> Vec<(Vec<String>, String)> {
        let source = declarations();
        let mut found = Vec::new();
        let mut nesting: Vec<String> = Vec::new();
        let mut buffer = String::new();

        for character in source.chars() {
            match character {
                // What was read since the last brace is this block's selector —
                // back to the last `;`, because a statement that is not a rule
                // (`@import`, `@source`) ends in one and is not part of it.
                '{' => {
                    let selector = buffer.rsplit(';').next().unwrap_or(&buffer);
                    nesting.push(selector.trim().to_owned());
                    buffer.clear();
                }
                '}' => {
                    if !buffer.trim().is_empty() {
                        found.push((nesting.clone(), buffer.clone()));
                    }
                    nesting.pop();
                    buffer.clear();
                }
                _ => buffer.push(character),
            }
        }
        found
    }

    /// The selector a rule is written under, which is the last of its nesting.
    fn selector(nesting: &[String]) -> &str {
        nesting.last().map(String::as_str).unwrap_or_default()
    }

    /// Every `(property, value)` a rule body declares.
    ///
    /// Split per rule *body* rather than over the file, which is the whole of
    /// why this is not one `split(';')`: a pseudo-class carries a colon, so
    /// `.chip:hover:not([aria-disabled="true"]) { color: … }` read flat parses
    /// as a property called `.chip` — and every declaration in every hover,
    /// focus and pressed rule in the sheet would sail past the tests below.
    fn declarations_of(body: &str) -> Vec<(String, String)> {
        body.split(';')
            .filter_map(|declaration| declaration.split_once(':'))
            .map(|(property, value)| (property.trim().to_owned(), value.trim().to_owned()))
            .collect()
    }

    /// The value a rule gives a property, if it gives it one.
    fn declared(selector: &str, property: &str) -> Option<String> {
        declarations_of(rule(selector))
            .into_iter()
            .find(|(name, _)| name == property)
            .map(|(_, value)| value)
    }

    /// Whether a rule declares a property at all.
    fn declares(body: &str, property: &str) -> bool {
        declarations_of(body)
            .iter()
            .any(|(name, _)| name == property)
    }

    /// The palette one scheme declares, as `(token, value)` — every hex in the
    /// block, which is every colour the scheme has.
    ///
    /// The three blocks are read by their own opening line, because they are
    /// three answers to the same question and a test that read the wrong one
    /// would pass on a palette nobody sees.
    fn scheme(opens: &str) -> Vec<(String, String)> {
        let source = declarations();
        let block = source
            .split_once(opens)
            .unwrap_or_else(|| panic!("`{opens}` opens a palette block"))
            .1
            .split_once("\n}")
            .expect("the palette block is closed")
            .0;

        declarations_of(block)
            .into_iter()
            .filter(|(name, value)| name.starts_with("--") && value.starts_with('#'))
            .collect()
    }

    /// One scheme's value for a token.
    fn value(scheme: &[(String, String)], token: &str) -> String {
        scheme
            .iter()
            .find(|(name, _)| name == token)
            .map(|(_, value)| value.clone())
            .unwrap_or_else(|| panic!("{token} is in the palette"))
    }

    /// WCAG relative luminance of a `#rrggbb`.
    fn luminance(hex: &str) -> f64 {
        let channel = |at: usize| {
            let value =
                u8::from_str_radix(&hex[at..at + 2], 16).expect("a hex pair") as f64 / 255.0;
            if value <= 0.03928 {
                value / 12.92
            } else {
                ((value + 0.055) / 1.055).powf(2.4)
            }
        };
        0.2126 * channel(1) + 0.7152 * channel(3) + 0.0722 * channel(5)
    }

    /// The contrast ratio between two `#rrggbb`, as WCAG defines it.
    fn contrast(first: &str, second: &str) -> f64 {
        let first = luminance(first);
        let second = luminance(second);
        (first.max(second) + 0.05) / (first.min(second) + 0.05)
    }

    /// Every declaration the vocabulary block makes, as `(name, value)`.
    ///
    /// Over the prose-stripped source, unlike [`rule`]: the vocabulary is where
    /// this stylesheet argues for itself at length, and a comment before a
    /// declaration would otherwise be read as part of its name.
    fn vocabulary() -> Vec<(String, String)> {
        declarations_of(
            declarations()
                .split_once("\n@theme static {")
                .expect("the vocabulary is one static theme block")
                .1
                .split_once("\n}")
                .expect("the block is closed")
                .0,
        )
    }

    /// Whether a namespace is cleared, *and* cleared before it is declared into.
    ///
    /// The order is the whole of it: `--color-*: initial` is a declaration like
    /// any other, and one written after the palette wipes the palette rather
    /// than Tailwind's.
    fn cleared_first(namespace: &str) -> bool {
        let prefix = namespace.trim_end_matches('*');
        let mut declared_into = false;

        for (name, value) in vocabulary() {
            if name == namespace {
                return !declared_into && value == "initial";
            }
            declared_into |= name.starts_with(prefix);
        }
        false
    }

    #[test]
    fn the_compiled_sheet_is_tailwinds_output() {
        // `include_str!` takes an empty file without complaining and so does
        // the window, which would open unpainted rather than fail to build.
        // Whether the committed artifact is what *this* source produces is
        // `npm run css:check`'s question and CI's, because answering it needs
        // Node; what a Rust toolchain can say is that something generated is
        // compiled in and that it carries the token contract.
        assert!(SHEET.starts_with("/*! tailwindcss"), "{:.40}", SHEET);
        assert!(SHEET.contains("--color-acc:"), "the tokens are in it");
    }

    #[test]
    fn no_comment_in_the_source_is_closed_twice() {
        // **A rule can leave this stylesheet without anything failing, and it
        // did.** This file is more prose than declaration by volume, and a
        // paragraph appended to a comment that was *already* closed leaves a
        // second `*/` behind it — which makes the sentences between the two
        // closes into CSS. Tailwind reads them as a malformed selector, drops
        // the rule that follows, and emits everything else without complaint.
        let source = declarations();
        assert!(
            !source.contains("*/"),
            "a comment is closed twice, which makes the prose between the two closes into CSS: {}",
            source
                .match_indices("*/")
                .map(|(at, _)| {
                    let from = source[..at].rfind('\n').map(|line| line + 1).unwrap_or(0);
                    source[from..at].trim()
                })
                .collect::<Vec<_>>()
                .join(" / ")
        );
    }

    #[test]
    fn the_document_declines_to_bounce() {
        // The shell has nothing to scroll by construction, and macOS bounces it
        // anyway (#74). Only the root element propagates `overscroll-behavior`
        // to the viewport, so `html` is the one element where declaring it says
        // anything at all.
        assert_eq!(
            declared("html", "overscroll-behavior").as_deref(),
            Some("none"),
        );
    }

    #[test]
    fn every_region_scrolls_as_a_screen_of_its_own() {
        // A scroller that reaches its end hands the rest of the gesture to
        // whatever is behind it, which is the web's rule and the reason a wheel
        // running off the end of the wire log used to carry on into the turn.
        let contained = rules()
            .into_iter()
            .find(|(_, body)| body.contains("overscroll-behavior: contain"))
            .map(|(nesting, _)| selector(&nesting).to_owned())
            .expect("the regions that scroll stop at their own end");

        // And every one of them is named: a scroller that is not in the set is
        // a region whose end hands the gesture to the window.
        for scroller in [
            ".rail-body",
            ".turn-stream",
            ".wire-rows",
            ".frame-json",
            ".lines",
            ".palette-list",
            ".slash-list",
            ".dialog-body",
            ".quoted",
            ".disclose-body",
        ] {
            assert!(
                contained.contains(scroller),
                "{scroller} scrolls, so it stops at its own end: {contained}"
            );
        }
    }

    #[test]
    fn the_scrollbars_are_the_windows_own_and_drawn_in_its_boundary_token() {
        // A WebView's default scrollbar is a browser's, in a palette that does
        // not change when the window goes dark, and this tool has ten scrollers.
        // Both spellings, because the two engines this shell runs on answer to
        // different ones.
        assert_eq!(declared("*", "scrollbar-width").as_deref(), Some("thin"));
        assert_eq!(
            declared("*", "scrollbar-color").as_deref(),
            Some("var(--line2) transparent"),
        );
        assert_eq!(
            declared("::-webkit-scrollbar-thumb", "background").as_deref(),
            Some("var(--line2)"),
        );
        for trough in ["::-webkit-scrollbar-track", "::-webkit-scrollbar-corner"] {
            assert_eq!(
                declared(trough, "background").as_deref(),
                Some("transparent"),
                "{trough} is not painted"
            );
        }
    }

    #[test]
    fn what_the_reader_is_doing_is_drawn_in_the_accent() {
        // The one hue this window spends on *the reader* rather than on the
        // agent: the value they set, the row they asked for, the control the
        // keyboard is on, and the text they have selected.
        assert_eq!(
            declared("::selection", "background").as_deref(),
            Some("var(--acc)"),
        );
        assert_eq!(
            declared("::selection", "color").as_deref(),
            Some("var(--acc-ink)"),
            "and the ink on it is the one the accent was given"
        );
        assert_eq!(
            declared(":is(.input, .textarea, textarea)", "caret-color").as_deref(),
            Some("var(--acc)"),
        );
        assert_eq!(
            declared("::placeholder", "color").as_deref(),
            Some("var(--dim2)"),
        );
        assert_eq!(declared("::placeholder", "opacity").as_deref(), Some("1"));
    }

    #[test]
    fn the_windows_own_words_are_not_selectable_and_the_agents_are() {
        // Dragging across this window selects what the agent said, what it sent
        // and what it was sent — never the words this window uses to label
        // them, which is the difference a reader feels between an application
        // and a page that looks like one.
        let chrome = rules()
            .into_iter()
            .find(|(_, body)| body.contains("user-select: none"))
            .map(|(nesting, _)| selector(&nesting).to_owned())
            .expect("the window's own words decline selection");

        for own in [
            ".bar",
            ".pane-head",
            ".rail-tabs",
            ".eyebrow",
            ".wire-filters",
            ".palette-foot",
            ".prompt-foot",
        ] {
            assert!(
                chrome.contains(own),
                "{own} is this window talking: {chrome}"
            );
        }
        // And nothing that carries what crossed the wire is in it. Every one of
        // these is evidence, and evidence a reader cannot copy out of the window
        // is evidence they have to retype.
        for evidence in [".said", ".raw", ".frame-json", ".quoted", ".line-text"] {
            assert!(
                !chrome.contains(evidence),
                "{evidence} carries what crossed and stays selectable: {chrome}"
            );
        }
    }

    #[test]
    fn the_window_is_a_bar_over_a_rail_and_two_screens() {
        // The drawing's arrangement, in the four rules that make it: a fixed bar,
        // a fixed rail, and the two screens sharing what is left — the turn
        // wider than the wire, because one is read and the other is scanned.
        assert_eq!(
            declared("#main", "flex-direction").as_deref(),
            Some("column")
        );
        assert_eq!(declared(".bar", "height").as_deref(), Some("52px"));
        assert_eq!(declared(".bar", "flex").as_deref(), Some("none"));
        assert_eq!(declared(".body", "flex").as_deref(), Some("1"));
        assert_eq!(declared(".body", "min-height").as_deref(), Some("0"));
        assert_eq!(declared(".rail", "width").as_deref(), Some("244px"));
        assert_eq!(declared(".rail", "flex").as_deref(), Some("none"));
        assert_eq!(declared(".split", "flex").as_deref(), Some("1"));
        assert_eq!(declared(".turns", "flex").as_deref(), Some("1.45"));
        assert_eq!(declared(".wire", "flex").as_deref(), Some("1"));
        // And every one of the four can be narrower than its content, which is
        // what stops a long agent string widening the window instead of eliding.
        for column in [".rail", ".split", ".turns", ".wire"] {
            assert!(
                declared(column, "min-width").as_deref() == Some("0")
                    || declared(column, "min-height").as_deref() == Some("0"),
                "{column} shrinks rather than pushing the window wider"
            );
        }
    }

    #[test]
    fn a_window_too_narrow_for_three_columns_shows_one_region_at_a_time() {
        // The drawing's answer below 1080: one region, and a bar at the foot to
        // choose between them. The chooser does not exist at full width — a
        // control for switching between three things that are all on screen is
        // three ways to do nothing.
        assert_eq!(declared(".mobile-bar", "display").as_deref(), Some("none"));

        let narrow = rules()
            .into_iter()
            .filter(|(nesting, _)| {
                nesting
                    .first()
                    .is_some_and(|at| at.contains("max-width: 1080px"))
            })
            .map(|(nesting, body)| (selector(&nesting).to_owned(), body))
            .collect::<Vec<_>>();
        assert!(
            !narrow.is_empty(),
            "the narrow window has answers of its own"
        );

        let said = |wanted: &str| {
            narrow
                .iter()
                .any(|(selector, body)| format!("{selector} {{{body}}}").contains(wanted))
        };
        for hidden in [
            ".body.on-rail .split",
            ".body:not(.on-rail) .rail",
            ".body.on-turn .wire",
            ".body.on-wire .turns",
        ] {
            assert!(
                narrow
                    .iter()
                    .any(|(selector, body)| selector == hidden && body.contains("display: none")),
                "{hidden} gives way when the window is too narrow for three columns"
            );
        }
        assert!(
            said("display: flex"),
            "and the chooser at the foot appears with them"
        );
    }

    #[test]
    fn the_lists_that_tail_are_laid_out_bottom_up() {
        // Three lists arrive newest-last and are read newest-first: the stream,
        // the wire log and the diagnostic channel. `column-reverse` is what
        // holds a streaming list at its own end without a scroll script — and
        // the last DOM child is the topmost one, which is why the free space
        // above a short list is given to it rather than below it.
        // The two that scroll themselves start at their own end, and a short
        // one of either sits at the bottom of the room it has: they are lists
        // of arriving lines, read newest-first, and a handful of rows floating
        // at the top of an empty panel reads as a panel that has not finished
        // drawing.
        for list in [".wire-rows", ".lines"] {
            assert_eq!(
                declared(list, "flex-direction").as_deref(),
                Some("column-reverse"),
                "{list} is laid out bottom-up"
            );
            assert_eq!(
                declared(list, "justify-content").as_deref(),
                Some("flex-start"),
                "{list} starts at its own end"
            );
            assert_eq!(
                declared(&format!("{list} > li:last-child"), "margin-top").as_deref(),
                Some("auto"),
                "and a short {list} sits at the bottom of the room it has"
            );
        }

        // The conversation is the same list read the same way round and is
        // packed the other way: the drawing starts a turn at the top of the
        // screen and lets it grow down to the composer, which is where a reader
        // scrolling back to the beginning of it expects the beginning to be.
        assert_eq!(
            declared(".stream", "flex-direction").as_deref(),
            Some("column-reverse"),
            "the newest entry is first in the document and last on screen"
        );
        assert_eq!(
            declared(".stream", "justify-content").as_deref(),
            Some("flex-end"),
            "and a short conversation reads from the top"
        );
    }

    #[test]
    fn the_way_back_to_the_newest_row_is_drawn_only_when_there_is_one() {
        // A control about the list rather than in it, so it is positioned
        // against the scroller and not against the window — and it is not drawn
        // at all while the list is at its tail, because a button that says *go
        // where you already are* is a button that teaches a reader to ignore it.
        assert_eq!(
            declared(".tailing", "position").as_deref(),
            Some("relative")
        );
        assert_eq!(
            declared(".tail-anchor", "position").as_deref(),
            Some("absolute")
        );
        assert_eq!(
            declared(".tail-anchor", "pointer-events").as_deref(),
            Some("none"),
            "the anchor is not in the way of the rows under it"
        );
        assert_eq!(
            declared(".to-latest", "pointer-events").as_deref(),
            Some("auto"),
            "and the button in it is"
        );
        let hidden = rule(
            "[data-tailed=\"true\"] + .tail-anchor .to-latest,\n.tailing:not(:has([data-tailed=\"false\"])) .to-latest",
        );
        assert!(
            hidden.contains("visibility: hidden") && hidden.contains("opacity: 0"),
            "a list at its tail offers no way back to it: {hidden}"
        );
    }

    #[test]
    fn nothing_taken_out_of_flow_is_positioned_against_the_window() {
        // Two things in this window are out of flow, and both are positioned
        // against the region they belong to: the way back to the newest row, and
        // the commands the agent published over the box they are typed into. A
        // third that answered to the viewport would be a panel that stayed put
        // while the region under it scrolled away.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            let Some((_, position)) = declarations_of(&body)
                .into_iter()
                .find(|(property, _)| property == "position")
            else {
                continue;
            };
            assert_ne!(
                position, "fixed",
                "`{selector}` is positioned against the window rather than against its region"
            );
            if position == "absolute" {
                assert!(
                    // The third is not a thing on the window at all: `.reach` is
                    // the clipped box a visually-hidden control is drawn in, and
                    // it is out of flow so that being off screen costs the row
                    // it is in no room (`timeline.rs`).
                    [".tail-anchor", ".slash", ".reach"].contains(&selector.as_str()),
                    "`{selector}` is out of flow and is not one of the three things that may be"
                );
            }
        }
        assert_eq!(
            declared(".composer-inner", "position").as_deref(),
            Some("relative"),
            "the commands are positioned against the composer"
        );
    }

    #[test]
    fn the_frame_a_reader_selected_is_read_in_a_pane_and_not_in_the_row() {
        // ADR 0009's answer to a per-row disclosure that pushed the list about
        // under the reader: the row is selected and the frame is read whole,
        // below the list, in a pane that is always the same size.
        assert_eq!(declared(".frame-pane", "flex").as_deref(), Some("none"));
        assert_eq!(declared(".frame-pane", "height").as_deref(), Some("44%"));
        assert_eq!(
            declared(".frame-pane", "min-height").as_deref(),
            Some("180px"),
            "a short window still reads a frame rather than a sliver of one"
        );
        assert_eq!(declared(".frame-json", "overflow").as_deref(), Some("auto"));
        assert_eq!(
            declared(".frame-json", "white-space").as_deref(),
            Some("pre"),
            "the bytes are laid out and never rewrapped"
        );
        // And the row that chose it says so where the reader's eye already is:
        // the near edge, in the accent, which is the same mark the palette and
        // the command list use for the row the keyboard is on.
        assert!(
            rule(".frame-row[aria-current=\"true\"]").contains("border-left-color: var(--acc)"),
            "the selected row is marked in the reader's own colour"
        );
    }

    #[test]
    fn a_payload_is_coloured_by_what_it_is_made_of_and_marked_no_other_way() {
        // `json.rs` is a lexer rather than a parser, and these five are the
        // whole of what it can say. Colour and nothing else: a payload that
        // bolded its keys would be this window emphasising part of a frame.
        for (part, token) in [
            (".json-key", "var(--key)"),
            (".json-string", "var(--str)"),
            (".json-number", "var(--num)"),
            (".json-literal", "var(--lit)"),
            (".json-punctuation", "var(--dim2)"),
        ] {
            assert_eq!(
                declared(part, "color").as_deref(),
                Some(token),
                "{part} is drawn in {token}"
            );
            assert_eq!(
                declarations_of(rule(part)).len(),
                1,
                "{part} says what it is with colour and nothing else"
            );
        }
    }

    #[test]
    fn an_entry_is_a_marked_gutter_and_the_content_beside_it() {
        // One column of glyphs down the left of the flow, so a streamed
        // conversation is scannable without reading every kind word — and the
        // mark is keyed on the tone, because what a column of marks is for is
        // what one row shares with another of its sort.
        assert_eq!(declared(".row", "display").as_deref(), Some("flex"));
        assert_eq!(declared(".row-mark", "width").as_deref(), Some("20px"));
        assert_eq!(declared(".row-mark", "flex").as_deref(), Some("none"));
        assert_eq!(declared(".row-body", "flex").as_deref(), Some("1"));
        assert_eq!(declared(".row-body", "min-width").as_deref(), Some("0"));

        // And the tone is the only thing it changes: a row that gained a ground
        // or a weight from its kind would be this window grading the traffic.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            if !selector.starts_with(".row.") || !selector.contains(".row-mark") {
                continue;
            }
            assert_eq!(
                declarations_of(&body)
                    .into_iter()
                    .map(|(property, _)| property)
                    .collect::<Vec<_>>(),
                vec!["color".to_owned()],
                "`{selector}` gives a kind more than its colour"
            );
        }
    }

    #[test]
    fn agent_provided_content_wraps_or_scrolls_on_its_local_axis() {
        // Everything an agent controls the length of, and what each of them does
        // about it. None of them widens the window: a session id, a path, a tool
        // name or a payload that pushed the layout would be an agent deciding
        // how wide this tool is.
        for wrapping in [
            ".said",
            ".raw",
            ".cap-name",
            ".cap-said",
            ".tile-endpoint",
            ".session-id",
            ".resource",
            ".blocking-title",
            ".blocking-meta",
            ".url-target",
            ".line .line-text",
        ] {
            let body = rule(wrapping);
            assert!(
                body.contains("overflow-wrap: anywhere") || body.contains("word-break: break-all"),
                "{wrapping} wraps rather than widening the window: {body}"
            );
        }
        // And the two that are quoted at length scroll inside their own box
        // rather than making the turn longer than the reader can scroll.
        let quoted = rule(".quoted, .tool-output");
        assert!(
            quoted.contains("max-height: 240px") && quoted.contains("overflow: auto"),
            "quoted output is bounded and scrolls on its own axis: {quoted}"
        );
        assert!(
            quoted.contains("white-space: pre-wrap"),
            "and it is drawn as it arrived: {quoted}"
        );
    }

    #[test]
    fn no_control_is_hidden_until_a_pointer_arrives() {
        // What is not drawn cannot be looked for, and a list that has to be
        // swept with a pointer to be read is a list that cannot be read at a
        // glance. Nothing in this window appears on hover.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            if !selector.contains(":hover") {
                continue;
            }
            for hiding in ["display", "visibility", "opacity"] {
                assert!(
                    !declares(&body, hiding),
                    "`{selector}` reveals or hides something with `{hiding}`: {body}"
                );
            }
        }
    }

    #[test]
    fn every_row_a_pointer_can_be_over_says_so() {
        // The four lists a reader points at, each answering the pointer the same
        // way: the ground the drawing gives a row under the cursor, and never a
        // colour that means something else.
        for row in [".row", ".slash-row", ".frame-line", ".palette-row"] {
            assert_eq!(
                declared(&format!("{row}:hover"), "background").as_deref(),
                Some("var(--panel2)"),
                "{row} says the pointer is over it"
            );
        }
    }

    #[test]
    fn every_control_family_has_the_same_visible_focus_indicator() {
        let everything = ":is(.btn, .input, .textarea, .select, .toggle, .checkbox, textarea, input, button, summary, a):focus-visible";
        let ring = rule(everything);

        assert!(
            ring.contains("outline: 2px solid var(--acc)") && ring.contains("outline-offset: 1px"),
            "one focus ring, in the reader's own colour: {ring}"
        );
        // Every control family is in it, and so is the bare element: a row that
        // is a `<button>` with a class of its own — a frame row, a palette row,
        // a mode row — takes the ring because it is a button, not because
        // somebody remembered to add it to a list.
        for control in [
            ".btn",
            ".input",
            ".textarea",
            ".select",
            "button",
            "summary",
        ] {
            assert!(
                everything.contains(control),
                "{control} takes the window's one focus ring"
            );
        }

        // **Two fields are drawn as the surface they are in**, so a ring around
        // the control inside would be a second boundary inside the first — and
        // neither of them goes without an indicator: what is exempted here has
        // to be answered there.
        let exempt = ":is(.prompt-box textarea, .palette-query):focus-visible";
        assert_eq!(
            declared(exempt, "outline").as_deref(),
            Some("none"),
            "the composer's field and the palette's question take no ring of their own"
        );
        assert_eq!(
            declared(".prompt-box:focus-within", "border-color").as_deref(),
            Some("var(--acc)"),
            "the composer says where the keyboard is on the box the field is in"
        );
        assert_eq!(
            declared(".palette-query:focus-visible", "border-bottom-color").as_deref(),
            Some("var(--acc)"),
            "and the palette says it on the rule under its question"
        );
        // And nothing else may join them: a rule that turned the ring off
        // anywhere else is a control the keyboard can reach and cannot be seen
        // on.
        for (nesting, body) in rules() {
            let turned_off = selector(&nesting).to_owned();
            if !turned_off.contains(":focus") || !body.contains("outline: none") {
                continue;
            }
            assert!(
                turned_off == exempt
                    // Not a control and not reachable by tabbing: `showModal`
                    // lands focus on the box so the keyboard starts inside the
                    // dialog, and a ring around the whole dialog says nothing
                    // about where anything is (`session.rs`).
                    || turned_off == ".dialog-box:focus",
                "`{turned_off}` turns off the focus indicator without drawing another"
            );
        }
    }

    #[test]
    fn a_reader_who_asked_for_less_motion_gets_none() {
        let reduced = rules()
            .into_iter()
            .find(|(nesting, _)| {
                nesting
                    .first()
                    .is_some_and(|at| at.contains("prefers-reduced-motion"))
            })
            .map(|(_, body)| body)
            .expect("the sheet answers a reader who asked for less motion");

        for declaration in [
            "animation-duration: 0.001ms !important",
            "animation-iteration-count: 1 !important",
            "transition-duration: 0.001ms !important",
            "scroll-behavior: auto !important",
        ] {
            assert!(
                reduced.contains(declaration),
                "reduced motion requires `{declaration}`: {reduced}"
            );
        }
    }

    #[test]
    fn the_two_things_that_move_on_their_own_are_the_drawings_own() {
        // **ADR 0009 reverses ADR 0004's rule against keyframes**, and reverses
        // it by exactly two: a row fades up as it arrives, and the dot beside a
        // stream that is open blinks while it is open. Both are the drawing's;
        // a third would be this window animating something the design does not.
        let keyframes = declarations()
            .match_indices("@keyframes")
            .map(|(at, _)| {
                declarations()[at..]
                    .split_whitespace()
                    .nth(1)
                    .expect("a keyframe is named")
                    .to_owned()
            })
            .collect::<Vec<_>>();
        assert_eq!(
            keyframes,
            ["blink", "fadeup"],
            "two animations, and they are the drawing's two"
        );

        // And everything that *transitions* is a control acknowledging the
        // pointer or the keyboard, which is what a transition is for.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            let Some((_, transition)) = declarations_of(&body)
                .into_iter()
                .find(|(property, _)| property == "transition")
            else {
                continue;
            };
            assert!(
                transition == "none"
                    || selector.contains(":hover")
                    || selector.contains(":focus")
                    || selector.contains("aria-pressed")
                    || selector.contains(".seg-item")
                    || selector.contains(".disclosure-icon"),
                "`{selector}` transitions something that is not interactive state: {transition}"
            );
        }
    }

    #[test]
    fn the_capitals_are_two_registers_and_both_are_the_drawings() {
        // A section's name, in the tracked label; and the tiny mark that names a
        // shape — a frame's envelope, a remembered invocation's transport — in
        // the tracked mark. Every rule that sets capitals sets one of the two,
        // so the register cannot be half-adopted somewhere else at some other
        // size.
        for (nesting, body) in rules() {
            if !body.contains("text-transform: uppercase") {
                continue;
            }
            let label = body.contains("font-size: var(--text-label)")
                && body.contains("letter-spacing: var(--tracking-label)");
            let mark = body.contains("font-size: var(--text-mark)")
                && body.contains("letter-spacing: var(--tracking-mark)");
            assert!(
                label || mark,
                "`{}` sets capitals outside the two registers they belong to: {body}",
                selector(&nesting)
            );
        }
    }

    #[test]
    fn every_size_in_the_window_is_a_step_of_the_scale() {
        // Seven sizes, and a rule that wanted an eighth would be inventing one
        // for one place. Dimensions stay written out — a 52px bar, a 20px
        // gutter, a 244px rail — because those are the size of a *thing* rather
        // than a step of a scale, and review should see and decide them.
        for (nesting, body) in rules() {
            for (property, value) in declarations_of(&body) {
                if property != "font-size" {
                    continue;
                }
                assert!(
                    value.starts_with("var(--text-") || value == "inherit",
                    "`{}` sets a size off the scale: {value}",
                    selector(&nesting)
                );
            }
        }
        // And the roles are the ones the drawing reads at: the window's body,
        // what the two parties said to each other, and the one field that is a
        // question.
        assert_eq!(
            declared("body", "font-size").as_deref(),
            Some("var(--text-body)")
        );
        assert_eq!(
            declared(".said", "font-size").as_deref(),
            Some("var(--text-read)")
        );
        assert_eq!(
            declared(".palette-query", "font-size").as_deref(),
            Some("var(--text-ask)")
        );
    }

    #[test]
    fn every_corner_is_a_step_of_the_drawings_ladder() {
        // **The drawing's radii are a ladder, not a scale**: the corner grows
        // with the thing it is on, a pixel at a time, and rounding it to five
        // steps left every control between 24 and 32 pixels a pixel or two off.
        // Each step is a token, so a rule cannot invent a tenth.
        let ladder = [
            ("--radius-chip", "0.3125rem"),
            ("--radius-control", "0.375rem"),
            ("--radius-button", "0.4375rem"),
            ("--radius-tile", "0.5rem"),
            ("--radius-card", "0.5625rem"),
            ("--radius-evidence", "0.625rem"),
            ("--radius-panel", "0.6875rem"),
            ("--radius-prompt", "0.8125rem"),
            ("--radius-dialog", "0.875rem"),
        ];
        for (step, drawn) in ladder {
            assert!(
                vocabulary()
                    .iter()
                    .any(|(name, value)| name == step && value == drawn),
                "{step} is the drawing's {drawn}"
            );
        }
        // **None of them is one of daisyUI's three**, which are set per theme
        // and would be the same declaration meaning two things.
        for daisy in ["--radius-field", "--radius-selector", "--radius-box"] {
            assert!(
                !vocabulary().iter().any(|(name, _)| name == daisy),
                "{daisy} is daisyUI's name for a corner and not this window's"
            );
        }

        for (nesting, body) in rules() {
            if nesting.iter().any(|at| at.contains("@plugin")) {
                continue;
            }
            for (property, value) in declarations_of(&body) {
                if !property.ends_with("radius") {
                    continue;
                }
                assert!(
                    value.starts_with("var(--radius-") || value == "0" || value == "50%",
                    "`{}` rounds `{property}` off the ladder: {value}",
                    selector(&nesting)
                );
            }
        }
    }

    #[test]
    fn the_controls_are_the_heights_the_drawing_draws_them_at() {
        // Written out rather than tokenised, because the height of a thing is
        // the size of that thing rather than a step of a scale — and read back
        // here so that a control cannot quietly come out a size smaller, which
        // is what happened when three of these were left to a component
        // library's `xs`.
        for (selector, height) in [
            (".bar", "52px"),
            (".pane-head", "40px"),
            (".frame-pane-head", "34px"),
            (".palette-query", "48px"),
            (".rail-tab", "30px"),
            (".seg-item", "26px"),
            (".mode-row", "30px"),
            (".mode-cycle", "26px"),
            (".palette-open", "30px"),
            (".chip", "20px"),
            (".dot", "7px"),
            (".tile-actions .btn, .rail-head .btn", "24px"),
            (".pane-head .btn", "26px"),
        ] {
            assert_eq!(
                declared(selector, "height").as_deref(),
                Some(height),
                "{selector} is {height} in the drawing"
            );
        }
    }

    #[test]
    fn the_surfaces_that_overlap_the_window_are_the_only_lifted_things() {
        // Three shadows in the vocabulary and nothing else casts one: the shade
        // under a segment that is on, the lift under something drawn over
        // content, and the box a dialog is. A ring around a request the turn
        // stopped on is a `box-shadow` too and is not a lift — it is the
        // drawing's own way of ringing the one thing waiting on the reader.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            for (property, value) in declarations_of(&body) {
                if property != "box-shadow" || value == "none" {
                    continue;
                }
                assert!(
                    value.starts_with("var(--shadow-")
                        || value.starts_with("inset")
                        || value.starts_with("0 0 0"),
                    "`{selector}` lifts something with a shadow of its own: {value}"
                );
            }
        }
        for lifted in [".slash", ".to-latest", ".dialog-box", ".toast .alert"] {
            assert!(
                rule(lifted).contains("var(--shadow-"),
                "{lifted} is over the window and says so"
            );
        }
    }

    #[test]
    fn a_request_the_turn_stopped_on_is_ringed_in_the_tone_of_what_it_is() {
        // The drawing rings the one thing the turn is waiting on, in the tone of
        // what is being asked: a permission in the direction colour the agent's
        // own traffic takes, an elicitation in the one hue that means *this
        // window has no name for it*. Answered, the ring goes and the box stays.
        assert!(
            rule(".blocking").contains("var(--in)") && rule(".blocking").contains("box-shadow"),
            "a request that is waiting is ringed"
        );
        assert!(
            rule(".blocking.elicit").contains("var(--vio)"),
            "and an elicitation is ringed as the other kind of ask"
        );
        assert_eq!(
            declared(".blocking.answered", "box-shadow").as_deref(),
            Some("none"),
            "a request that has been answered is no longer waiting on anybody"
        );
    }

    #[test]
    fn the_composer_is_one_bounded_field_with_its_footer_inside_it() {
        // The drawing's composer is one box: the field, and under it the row of
        // what pressing return does. The `textarea` inside it has no boundary of
        // its own — two nested boxes is what it looked like before — and the box
        // takes the accent when the keyboard is in it.
        assert!(
            rule(".prompt-box").contains("border: 1px solid var(--line2)"),
            "the composer is one bounded field"
        );
        assert_eq!(
            declared(".prompt-box:focus-within", "border-color").as_deref(),
            Some("var(--acc)"),
            "and it says when the keyboard is in it"
        );
        let field = rule(".prompt-box textarea");
        assert!(
            field.contains("border: none")
                && field.contains("outline: none")
                && field.contains("background: transparent"),
            "the field inside it draws no second box: {field}"
        );
        assert!(
            field.contains("resize: none") && field.contains("field-sizing: content"),
            "it grows with what is typed rather than being dragged: {field}"
        );
        assert!(
            rule(".prompt-foot").contains("border-top: 1px solid var(--line)"),
            "and the footer is a band of the same box"
        );
    }

    #[test]
    fn an_empty_screen_is_centred_in_the_room_it_has() {
        // Two of the empties in this window are the whole of a screen — a turn
        // with no session in it, a wire log with nothing on it — and a sentence
        // set hard against the top left of a 900px canvas reads as a screen that
        // has not finished drawing rather than as the state it is.
        let empty = rule(".empty");
        for declaration in [
            "align-items: center",
            "justify-content: center",
            "text-align: center",
            "text-wrap: balance",
        ] {
            assert!(
                empty.contains(declaration),
                "an empty screen requires `{declaration}`: {empty}"
            );
        }
    }

    #[test]
    fn no_rule_singles_out_one_advertisers_claims() {
        // Both accounts are drawn identically (#86): who claimed a thing is the
        // point of showing it, and a stylesheet that made one of the two an
        // aside would be answering the question the screen exists to ask.
        for (nesting, _) in rules() {
            let selector = selector(&nesting);
            assert!(
                !selector.contains("data-advertiser") && !selector.contains("data-identity"),
                "`{selector}` draws one advertiser's claims differently from the other's"
            );
        }
    }

    #[test]
    fn the_vocabulary_is_emitted_whether_or_not_a_utility_uses_it() {
        // `static`, and it is load-bearing rather than tidy: Tailwind drops a
        // theme variable no utility mentions, and the rules in `input.css` name
        // these tokens in `var()` — which is not a utility and not something the
        // scanner counts.
        assert!(
            SOURCE.contains("\n@theme static {"),
            "the vocabulary is one static theme block"
        );
    }

    #[test]
    fn a_utility_can_paint_with_no_colour_but_this_windows_own() {
        // The colour-literal test below reads the rules a person writes; it
        // cannot see `bg-red-500` in a Rust file, and Tailwind's default palette
        // would make that class real. Clearing the namespace is what makes it
        // *not exist*.
        assert!(
            cleared_first("--color-*"),
            "the default palette is not cleared before ours is declared"
        );

        for (name, value) in vocabulary() {
            if !name.starts_with("--color-") || name == "--color-*" {
                continue;
            }
            assert!(
                value.starts_with("var(--")
                    || matches!(value.as_str(), "transparent" | "currentColor"),
                "{name} is painted from something other than a token: {value}"
            );
        }
    }

    #[test]
    fn production_uses_only_the_custom_unprefixed_inspector_themes() {
        let declarations = declarations();

        assert!(
            declarations.contains("@plugin \"daisyui\"")
                && declarations.contains("themes: false")
                && declarations.contains("name: \"inspector-light\"")
                && declarations.contains("name: \"inspector-dark\"")
                && declarations.contains("default: true")
                && declarations.contains("prefersdark: true")
                && !declarations.contains("prefix:"),
            "production selects only the unprefixed Inspector themes at the Appearance seam"
        );
        // **`list` is not among the components included**, and that is a
        // decision rather than an omission: every list in this window is an
        // evidence surface with a layout of its own, and a component whose every
        // use is a rewrite is not owning anything.
        assert!(
            !declarations.contains(" list,"),
            "daisyUI's list is not included"
        );
        assert!(
            SHEET.contains(".btn")
                && SHEET.contains(".input")
                && SHEET.contains(".select")
                && SHEET.contains(".textarea")
                && SHEET.contains(".badge")
                && SHEET.contains(".alert")
                && SHEET.contains(".toggle")
                && SHEET.contains(".toast")
                // The three surfaces that are over the window rather than in it:
                // the launch dialog, the sessions dialog, and the palette.
                && SHEET.contains(".modal")
                && SHEET.contains("[data-theme=\"inspector-light\"]")
                && SHEET.contains("[data-theme=\"inspector-dark\"]")
                && SHEET.contains("@media (prefers-color-scheme: dark)")
                && SHEET.contains(":root:not([data-theme])"),
            "the committed stylesheet contains both explicit themes and OS-driven System"
        );
    }

    #[test]
    fn the_themes_carry_the_drawings_control_unit() {
        // daisyUI sizes a control off one unit, and the drawing's is 3.25px:
        // 19.5px at `xs`, 26px at `sm`, 32.5px at `md` — the three heights it
        // draws. Flat, because the drawing's buttons are a boundary and a
        // ground, and the one thing that carries a shadow says so itself.
        for name in ["inspector-light", "inspector-dark"] {
            let opens = format!("name: \"{name}\";");
            let theme = SOURCE
                .split_once(opens.as_str())
                .expect("both themes are declared")
                .1
                .split_once("\n}")
                .expect("the theme block is closed")
                .0;
            for declaration in [
                "--size-field: 0.203125rem",
                "--size-selector: 0.203125rem",
                "--radius-selector: 0.3125rem",
                "--radius-field: 0.375rem",
                "--radius-box: 0.6875rem",
                "--border: 1px",
                "--depth: 0",
                "--noise: 0",
            ] {
                assert!(
                    theme.contains(declaration),
                    "{name} must provide `{declaration}` to daisyUI components"
                );
            }
        }
    }

    #[test]
    fn daisyui_components_are_repainted_rather_than_reimplemented() {
        // daisyUI keeps the geometry, the states and the accessibility; these
        // rules say what the drawing paints them in, and they say it in
        // daisyUI's own variables wherever there is one. A rule that gave a
        // component its own height or its own layout would be a component this
        // window had rewritten and would have to go on rewriting.
        let paint = [
            "background",
            "background-color",
            "color",
            "border-color",
            "border-radius",
            "box-shadow",
            "font-family",
            "font-size",
            "font-weight",
            "font-variant-numeric",
            "letter-spacing",
            "text-decoration",
            "opacity",
            "cursor",
            "caret-color",
        ];
        for component in [
            ".btn",
            ".input, .textarea, .select",
            ".badge",
            ".toggle",
            ".checkbox",
        ] {
            for (property, _) in declarations_of(rule(component)) {
                assert!(
                    property.starts_with("--") || paint.contains(&property.as_str()),
                    "`{component}` declares `{property}`, which is daisyUI's to decide"
                );
            }
        }
        // **`.alert` is the one component drawn as a box of this window's own**,
        // and it is named here rather than left to be noticed: the drawing's
        // notice is a hairline in the tone of what it is about, where daisyUI's
        // is a filled grid, and every notice in this window is a sentence about
        // the agent rather than a banner about the tool.
        let alert = rule(".alert");
        assert!(
            alert.contains("border: 1px solid var(--line)")
                && alert.contains("background: var(--panel2)")
                && alert.contains("box-shadow: none"),
            "the notice is a hairline box rather than a fill: {alert}"
        );
    }

    #[test]
    fn dark_is_written_twice_and_the_two_are_the_same_palette() {
        // CSS has no way to say "these declarations, under either of two
        // conditions": System on a dark desktop reads the media query and an
        // explicit Dark reads the attribute. A change to one is a change owed to
        // the other, and this is what makes that a build failure rather than a
        // thing review has to catch — it missed it the first time it mattered,
        // and the half it missed was the half `Appearance → Dark` shows.
        let system = scheme("\n  :root:not([data-theme]) {");
        let chosen = scheme("\n[data-theme=\"inspector-dark\"] {");

        assert!(!system.is_empty(), "System's dark palette is declared");
        assert_eq!(
            system, chosen,
            "the two ways of asking for dark are the same palette"
        );
    }

    #[test]
    fn the_palette_is_the_drawings_and_every_value_below_the_text_floor_is_named() {
        // WCAG AA, measured rather than eyeballed: 4.5:1 for text on every
        // ground it rests on, 3:1 for a signal. The palette is the drawing's, so
        // three of its values do not clear the text floor — and the point of
        // this test is that they are *named*, that they are held where they are,
        // and that a fourth cannot join them quietly (ADR 0009).
        const GROUNDS: [&str; 4] = ["--bg", "--panel", "--panel2", "--sunk"];
        const INK: [&str; 13] = [
            "--txt", "--dim", "--dim2", "--acc", "--out", "--in", "--ok", "--err", "--vio",
            "--key", "--str", "--num", "--lit",
        ];

        for (name, palette, below) in [
            (
                "light",
                scheme("\n:root {"),
                // The drawing's own, and the worst ratio each of them reaches on
                // any of the four grounds. Every one of them says what it means
                // a second way — a word on the row, an arrow, a position — and
                // every one clears the 3:1 a signal owes.
                vec![("--dim2", 3.05), ("--out", 4.40), ("--ok", 3.83)],
            ),
            (
                "dark",
                scheme("\n[data-theme=\"inspector-dark\"] {"),
                vec![("--dim2", 3.66)],
            ),
        ] {
            for token in INK {
                let worst = GROUNDS
                    .into_iter()
                    .map(|ground| contrast(&value(&palette, token), &value(&palette, ground)))
                    .fold(f64::INFINITY, f64::min);

                match below.iter().find(|(named, _)| *named == token) {
                    // A named exception, held where the drawing put it: lower is
                    // a regression and higher means the record is stale.
                    Some((_, recorded)) => assert!(
                        (worst - recorded).abs() < 0.01,
                        "{name} {token} is {worst:.2}:1 and is recorded as {recorded:.2}:1"
                    ),
                    None => assert!(
                        worst >= 4.5,
                        "{name} {token} is text at {worst:.2}:1 and is not one of the named exceptions"
                    ),
                }
                assert!(
                    worst >= 3.0,
                    "{name} {token} is below the floor a signal owes: {worst:.2}:1"
                );
            }

            // The ink the accent was given, on the accent: the one filled
            // control on any surface.
            assert!(
                contrast(&value(&palette, "--acc-ink"), &value(&palette, "--acc")) >= 4.5,
                "{name} the ink on a filled control clears the text floor"
            );
        }
    }

    #[test]
    fn no_rule_outside_the_palette_blocks_carries_a_colour_literal() {
        // **Every colour in this sheet is a token**, and a literal anywhere else
        // is a rule that only works in one scheme — the whole failure mode this
        // arrangement exists to make impossible. The blocks where the values
        // live are the two daisyUI themes and the three palette blocks.
        for (nesting, body) in rules() {
            let selector = selector(&nesting).to_owned();
            if nesting.iter().any(|at| at.contains("@plugin"))
                || selector.contains("@theme")
                || selector == ":root"
                || selector == ":root:not([data-theme])"
                || selector == "[data-theme=\"inspector-dark\"]"
            {
                continue;
            }
            for (property, value) in declarations_of(&body) {
                assert!(
                    !value.contains('#')
                        && !value.contains("rgb(")
                        && !value.contains("rgba(")
                        && !value.contains("hsl(")
                        && !value.contains("oklch(")
                        && !value.contains("oklab("),
                    "`{selector}` paints `{property}` with a literal: {value}"
                );
            }
        }
    }
}
